version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/STIL.ServiceClient"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only

  - package-ecosystem: "nuget"
    directory: "/src/STIL.ServiceClient.Tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
